#!/bin/bash

me=`readlink $0`
if [ "x${me}" == "x" ]
then
        me=$0
fi
curdir=`dirname ${me}`

source ${curdir}/utils_basic
file_name_info="file_info"
QSM_AE=MacServer


if [ "$1" == "" ]
then
	echo "${me} <dir>"
	echo "  Show all series for the exam found in <dir>"
fi

if ! [ -e "$1" ]
then
	echo File $1 not found. Exiting...
	exit 1
fi

file_scanner_list="${curdir}/../etc/scanner_list"


dcmfile=`find ${1}/ -type f | grep -v ${file_name_info} | head -n 1`
if [ "$dcmfile" == "" ]
then
	echo No dicoms found. Exiting
	exit 1
fi

AET_peer=`get_dcm_field $dcmfile 0002,0016`
IP_peer=`sed -n '1! p' ${file_scanner_list} | awk '$2=="'${AET_peer}'" {print $3}'`
port_peer=`sed -n '1! p' ${file_scanner_list} | awk '$2=="'${AET_peer}'" {print $4}'`

StudyDate=`get_dcm_field $dcmfile 0008,0020`
StudyInstanceUID=`get_dcm_field $dcmfile 0020,000d`
PatientID=`get_dcm_field $dcmfile 0010,0020`
SOPInstanceUID=

showtmpdir=${folder_buffer}/showtmp
mkdir -p ${showtmpdir}
log_show=${folder_buffer}/log_stdout_dcmshow

echo >> ${log_show}
log ${1} >> ${log_show} 
echo "StudyInstanceUID = ${StudyInstanceUID}" >> ${log_show}
echo "AET_peer         = ${AET_peer}" >> ${log_show}

qry=${showtmpdir}/patqry.${StudyInstanceUID}
cat <<EOF > ${qry}.txt
# query patient names and IDs
(0008,0052) CS [SERIES]                # QueryRetrieveLevel
(0008,0020) DA [${StudyDate}]          # StudyDate
(0010,0020) LO [${PatientID}]          # PatientID
(0020,000d) UI [${StudyInstanceUID}]   # StudyInstanceUID 
(0020,000e) UI [*]                     # SeriesInstanceUID
(0008,103e) LO [*QSM*]                 # SeriesDescription
EOF
dump2dcm ${qry}.txt ${qry}.dcm >> ${log_show} 2>&1

rspdir=${qry}.rsp
mkdir -p ${rspdir}
cd ${rspdir}
findscu -X -P ${IP_peer} ${port_peer} -aec ${AET_peer} ${qry}.dcm 
echo movescu -v --move ${QSM_AE} ${IP_peer} ${port_peer} -aec ${AET_peer} -aet ${QSM_AE} ${rspdir}/rsp*dcm

#>> ${log_show} 2>&1
