#!/bin/bash

me=`readlink $0`
if [ "x${me}" == "x" ]
then
        me=$0
fi
curdir=`dirname ${me}`


TARBALL=$1
SCANNER=$2
EXNO=$3
SENO=$4


# Merge into Active Routine
destination="${curdir}/../buffer/tmp"

# Make new tmp folder
folder_name="temp_"`date +"%Y%m%d_%H%M%S"`"_GE_${SCANNER}"	# Assume this is unique
mkdir -p ${destination}/${folder_name}
tar xvfj /home/sdc/${TARBALL} -C ${destination}/${folder_name}
rm /home/sdc/${TARBALL}
# Create info file
file_name="file_info"
time_stamp=`date +"date %Y-%m-%d time %H:%M"`
echo ${SCANNER} > ${destination}/${folder_name}/${file_name}
echo $time_stamp >> ${destination}/${folder_name}/${file_name}
echo "Info file created"


