#!/bin/bash

me=`readlink $0`
if [ "x${me}" == "x" ]
then
        me=$0
fi
curdir=`dirname ${me}`

# Start all processes for checking automatic QSM reconstruction
${curdir}/check_auto_QSM >> ${curdir}/../buffer/log_stdout_daemon 2>&1
