#!/bin/bash

me=`readlink $0`
if [ "x${me}" == "x" ]
then
        me=$0
fi
curdir=`dirname ${me}`

source ${curdir}/setup_config


log()
{
	echo -n $(date +"[date %Y-%m-%d time %H:%M:%S]:")
	echo "${@}"
}


get_folder_size()
{
	if [ $(uname) == "Darwin" ]
	then
		du ${3} -d ${2} ${1}
	else
		du ${3} --max-depth ${2} ${1}
	fi
}


get_dcm_field()
{
	${DCMDUMP} +P ${2} ${1} 2>/dev/null | awk '{print $3}' | tr -d "[]"
}

get_gdcm_field()
{
	${GDCMDUMP} -C ${1} 2>/dev/null | grep $2 |  awk '{print $3}'
}


crop_file()
{
	local file_name=${1}
	local line_num=${2}

	local n_line=$(cat ${file_name} | wc -l)

	# File too small
	while [ ${n_line} -lt ${line_num} ]
	do
		echo "" | cat >> ${file_name}
		n_line=$[${n_line}+1]
	done	

	# File too large
	if [ ${n_line} -gt ${line_num} ]
	then
		sed -n -i "1,${line_num}p" ${file_name}
	fi	
}


check_status_QSM()
{	
	local status_QSM=

	if [ "$(cat ${file_condition_QSM} 2>/dev/null)" == "0" ] && \
	   [ "$(cat ${file_job_logbook} 2>/dev/null | wc -l)" -eq 0 ]
	then
		status_QSM="idle"
	else
		status_QSM="running"
	fi

	echo ${status_QSM}
}


is_idle()
{
	[ "$(check_status_QSM)" == "idle" ] && return 0 || return 1
}


parse_path()
{
	eval ${4}=\"$(echo ${1} | rev | cut -d'/' -f1 | rev)\"
	eval ${3}=\"$(echo ${1} | rev | cut -d'/' -f2 | rev)\"
	eval ${2}=\"$(echo ${1} | rev | cut -d'/' -f3 | rev)\"
}


check_sum_folder()
{
	local fd1=${1}
	local fd2=${2}
	echo "Check Sum for Folder:" ${fd1} ${fd2}

	[ ! -d "${fd1}" ] || [ ! -d "${fd2}" ] && return 1

	local sum1=$(find ${fd1} -type f -exec md5sum -b {} \; | awk '{print $1}' | sort | md5sum -b | awk '{print $1}')
	local sum2=$(find ${fd2} -type f -exec md5sum -b {} \; | awk '{print $1}' | sort | md5sum -b | awk '{print $1}')

	echo ${sum1} ${sum2}

	[ "${sum1}" == "${sum2}" ] && return 0 || return 1
}


